fix typo
TomDoesTech/REST-API-Tutorial-Updated pull request #11
Opened 2022-06-13 14:42 UTC by aliensb

2022-07-10 16:42 UTC, Samtaylek17 approved these changes

2022-07-10 16:42 UTC, Samtaylek17 approved these changes

2022-08-21 07:58 UTC, retconned requested changes
Fixed a typo in user.schema.ts

Everything seems good!

2023-02-28 05:32 UTC, tomanagle commented
Thanks!

2023-02-28 05:32 UTC, merged